### PR TITLE
Fix enum protocol type

### PR DESCRIPTION
**Pull request by pkerling**
The scanner operated under the assumption that enums always get sent as uint32_t, which is not the case. Wayland wire protocol specifies that "the enum attribute can be used on either uint or int arguments."

I've added the `dump` example to show the error in action. It will crash if you try to run it without the scanner fix.

### CODE REVIEW

**Comment by NilsBrause** [comment]
Interesting. I will have a look at that this weekend and try to understand why this is necessary. In the meantime, please change "\n" to std::endl. Also put your name in the copyright of the dump example, since you wrote it yourself. :)

**Comment by pkerling** [comment]
done - maybe you find a better/more natural way to fix this, but it does need to get fixed some way or the other

**Comment by NilsBrause** [comment]
I have now looked into it and found the cause. Since this field is marked is "int" in the XML, the c_dispatcher puts an int32_t into the any container. And when the output dispatcher tries to extract an uint32_t, it throws a bad_cast.

There are now to ways to fix this:
- Change the "int" to an "uint" in the XML.
- Fix the scanner

Since I would like to keep the modifications to the XML as small as possible, I will use your fix. :)

Thank you very much for pointing that out! :)

**Comment by pkerling** [comment]
Thanks for merging - I also think that changing the XML is not a good idea if it can be handled correctly in the code instead. It makes upgrading the protocol to new versions more difficult. Also I'm not sure if it would even work since you will probably get a protocol mismatch error between server and client then.

**Comment by NilsBrause** [comment]
Don't worry. There are only seven changes in total. Six of them, where upstream forgot the "enum" attribute and one, where upstream forgot the bitfield attribute. Those changes don't affect the wire protocol at all. They only affect the C++ interface. You can have a look at the changes here:
https://github.com/NilsBrause/Wayland/commit/a6329b417f125ddf8a719a7e430409f3b2926513

**Comment by pkerling** [comment]
I can see the missing enum attributes, but why do you think the transform should be a bitfield? The enumeration values seem very much mutually exclusive to me.

**Comment by NilsBrause** [comment]
The definition of a bitfield is that each bit has a distinct meaning, which is
the case for the enumeration wl_output.transform:

- bit 0: rotate by 90 degree
- bit 1: rotate by 180 degree
- bit 2: flip around vertical axis

Every other value can be constructed by ORing together the above bits:

- "270" = "90" | "180"
- "flipped_90" = "90" | "flipped"
- "flipped_180" = "180" | "flipped"
- "flipped_270" = "90" | "180" | "flipped"

Therefore I added the bitfield="true" attribute to the enumeration declaration.

More than one and a half years ago, I already tried to explain this on the upstream mailing list, but they refused to understand.

**Comment by pkerling** [comment]
Ah yes, I get your point. I personally find it highly confusing to mix discrete values that you must match for equality (`normal`) and values that can be both discrete and ORed (e.g. `90` with equality comparison means exactly 90 degrees non-flipped, but it can also be checked as flag). In my opinion, bitfield entry definitions should only have powers of two in the `value` fields.

It seems the Wayland protocol does this mixing at one other occasion (`resize` enum in `wl_shell_surface`), but then again `wl_shell_surface` is practically abandoned and has some design problems anyway…

**Comment by NilsBrause** [comment]
I agree, it is somewhat confusing. But being able to check if the output is flipped with a simple and is worth it, I think. ;)

Indeed, wl_shell_surface.resize looks like a bitfield, too. I missed that, thanks. :) Even if this interface is abandoned, I will add the bitfield attribute.

**Pull request merged**
