### PR TITLE
Make it clear that the whole project is covered by GPL 3.0 or later

### PR DESCRIPTION
**Pull request by rbalint**
The original LICENSE starts with:
```
See each file for details on licensing.
...
```
Since some files lack licensing information their license was not clear.

### CODE REVIEW

**Comment by rbalint** [comment]
@NilsBrause Please accept the patch or clarify the license by other means because the current state prevents the inclusion of the packaged version in the official Debian and Ubuntu archives and in general makes the source code safely undistributable legally.

**Comment by rbalint** [comment]
This also blocks packaging Kodi in the distributions.

**Comment by NilsBrause** [comment]
Not the whole project is GPL 3.0 licensed. Just the scanner. All source that is linked against by other programs is licenced under a BSD style license, so that it can be used by closed source software as well. I will clarify the licensing of the remainin files later today. Sorry for the inconvenience.

**Comment by rbalint** [comment]
Thanks! If you could make a new release with the changes, that would help a lot in packaging waylandpp cleanly.

**Comment by NilsBrause** [comment]
I have added missing license information and update existing copyrights. Please take a look whether this is sufficient. If so, I'll issue another release.

**Comment by rbalint** [comment]
@NilsBrause Strictly speaking the license of README.md is not clarified yet, but thank you for adding license for almost all the files.
I think it would be nicer to say something like "The project's files are provided under the following license unless stated otherwise in the individual files" in LICENSE/COPYING rather than adding a license to README.md as well.

**Comment by NilsBrause** [comment]
Done. Thanks for your input!

**Pull request closed without merging**
