### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by pkerling**
Hey,
these are various improvements to the CMake build system and doc building. I can extract to separate PRs if you only want to take some of them.

@wsnipex please confirm whether https://github.com/NilsBrause/waylandpp/commit/e0189ff6f1e43ccbd672d272487033c999887772 fixes your issue

### CODE REVIEW

**Comment by wsnipex** [comment]
thanks, looks good, this fixes the packaging issue.

fyi: waylandpp packages for ubuntu 17.10 are available in our nightly PPA:
https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly

This probably will lead to it being pulled into debian as well, once we release kodi 18

**Comment by NilsBrause** [comment]
Hi! Thanks for the work! The commit "[CMake] Use standard GNUInstallDirs module for install directories" makes the pkgconfig directory not configurable anymore. Is this intended?

**Comment by NilsBrause** [comment]
@wsnipex What were the packaging issues you were having?

**Comment by wsnipex** [comment]
hardcoding install paths made it impossible to package it as debian multi-arch

**Comment by NilsBrause** [comment]
@wsnipex I thought we already had every possible path configurable with out INSTALL_*_DIR variables that we had before. But I will pull that anyway, since using GNUInstallDirs is much more elegant.

I will probably also drop SCons soon, since I don't want to maintain two build systems anymore. Eventhough crosscompiling is much harder with CMake. But everyone seems to prefer that for some reason.

**Comment by pkerling** [comment]
> Hi! Thanks for the work! The commit "[CMake] Use standard GNUInstallDirs module for install directories" makes the pkgconfig directory not configurable anymore. Is this intended?

You merged it already, but yes it was intentional :-) I'm not sure why I had it configurable before.

**Pull request merged**
